### ISSUE TITLE
Differentiate `ci` and `test` in Commit Message (RDT-612)

### ISSUE THREAD

**Issue by hfudev** [espressif/conventional-precommit-linter#18]
according to https://github.com/espressif/conventional-precommit-linter/blob/master/conventional_precommit_linter/hook.py#L14, the default type does not include `test`

The commits with the prefix `ci:` should not be used for test script changes. It should be used with CI related changes. For test script changes, we should use `test:` instead.

The separation will help us maintain clarity and consistency in our commit history. Also helps find the correct commits that needs to be backported.

**Comment by tomassebestik** [comment]
@hfudev Is the proposal to expand the default types for the `test` type by adding it to `DEFAULT_TYPES = ['change', 'ci', 'docs', 'feat', 'fix', 'refactor', 'remove', 'revert', 'test']`? 

If so, we should consider updating also the Danger defaults for consistency:

- [GitHub - shared-github-dangerjs](https://github.com/espressif/shared-github-dangerjs/blob/v1/src/configParameters.ts#L18)
- [GitLab - shared-ci-dangerjs](https://gitlab.espressif.cn:6688/espressif/shared-ci-dangerjs/-/blob/master/src/configParameters.ts?ref_type=heads#L13)

**Comment by hfudev** [comment]
yes, please. thank you! and I've removed the internal url link...

**Comment by tomassebestik** [comment]
@hfudev I have one more question/doubt: 

Does "For test script changes" refer to modifications in actual test scripts (e.g., Python scripts) or to any kind of "test" action in MR/PR?

Developers could use commit messages like `test: testing if this thing works` for temporary commits. If we include `test` in the default values, such temporary messages might stay undetected.

**Comment by tomassebestik** [comment]
Released in version [v1.6.0](https://github.com/espressif/conventional-precommit-linter/releases/tag/v1.6.0)
