### ISSUE TITLE
[RFC] Remove restriction "'summary' must start with a capital letter" (RDT-489)

### ISSUE THREAD

**Issue by hfudev** [espressif/conventional-precommit-linter#2]
all the examples listed in the https://www.conventionalcommits.org/en/v1.0.0/ got the first letter with lower case.

**Comment by tomassebestik** [comment]
Solved in PR #3 . Uppercase is now only optional, the default setting (without arguments) does not enforce capitalization.
Thank you @hfudev for the idea and PR review.
