### ISSUE TITLE
Feature request: Add a spell check (RDT-830)

### ISSUE THREAD

**Issue by peterdragun** [espressif/conventional-precommit-linter#28]
It would be nice if as part of checking the conventional commit style, we would have some spell check. Something similar to the codespell pre-commit check would be helpful. Please also consider adding an option to define ignore words.

**Comment by tomassebestik** [comment]
As much as I like the idea of improving the commit linter, this seems to be beyond the scope of the tool. 

I'm afraid that adding complexity to the clear and simple code will not pay off. With a spellchecker, we would probably need to maintain a set of exceptions. Also, commit messages can use some abbreviations that would likely be detected as typos.
